global:
  scrape_interval: 15s
  external_labels:
    monitor: "Monitoring"
scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
  - job_name: "cAdvisor"
    static_configs:
      - targets: ["cadvisor:8080"]
